/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import control.ClientCtr;
import java.awt.Frame;
import javax.swing.JOptionPane;
import model.ObjectWrapper;
import model.Friend;
import model.User;

/**
 *
 * @author son
 */
public class UserDetailFrm extends javax.swing.JDialog {

    /**
     * Creates new form UserDetail
     */
    private ClientCtr clientCtr;
    private User user1;
    private User user2;
    private Friend friend;

    public UserDetailFrm(Frame parent, boolean modal, User user1, User user2, ClientCtr clientCtr) {
        super(parent, modal);
        initComponents();
        this.user1 = user1;
        this.user2 = user2;
        this.clientCtr = clientCtr;
        this.clientCtr.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_GET_FRIEND_BY_USER, this));
        this.clientCtr.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_ADD_FRIEND, this));
        this.clientCtr.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_CANCEL_FRIEND, this));
        this.clientCtr.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_CONFIRM_FRIEND, this));
        getFriend();
    }

    private void getFriend() {
        Friend input = new Friend();
        input.setUser_1(user1);
        input.setUser_2(user2);
        this.clientCtr.sendData(new ObjectWrapper(ObjectWrapper.GET_FRIEND_BY_USER, input));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        acceptBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        username.setText("jLabel1");

        addBtn.setText("Add friend");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        acceptBtn.setText("Accept");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("CancelRequest");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(username))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(username)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(acceptBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        Friend input = new Friend();
        input.setUser_1(user1);
        input.setUser_2(user2);
        input.setConfirmed(false);
        clientCtr.sendData(new ObjectWrapper(ObjectWrapper.ADD_FRIEND, input));
    }//GEN-LAST:event_addBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        clientCtr.sendData(new ObjectWrapper(ObjectWrapper.CANCEL_FRIEND, this.friend));
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        this.friend.setConfirmed(true);
        clientCtr.sendData(new ObjectWrapper(ObjectWrapper.CONFIRM_FRIEND, this.friend));
    }//GEN-LAST:event_acceptBtnActionPerformed

    public void receivedDataProcessing(ObjectWrapper data) {
        resetUI();
        if (data.getPerformative() == ObjectWrapper.REPLY_GET_FRIEND_BY_USER) {
            this.friend = (Friend) data.getData();
            System.out.println(this.friend.getId() + " " + this.friend.isConfirmed() + " " + this.friend.getUser_1().getUsername() + " " + this.friend.getUser_2().getUsername());
            // update button status
            if (this.friend.getId() != null) {
                if (this.friend.isConfirmed() == false) {
                    if (this.friend.getUser_1().getId().equals(this.user1.getId())) {
                        // if you are the one to send the request
                        // you can cancel it
                        cancelBtn.setEnabled(true);
                    } else {
                        // you can accept request from that user
                        acceptBtn.setEnabled(true);
                    }
                }
            } else {
                addBtn.setEnabled(true);
            }

            // update username label
            if (this.friend.getUser_2().getId().equals(this.user2.getId())) {
                username.setText(this.friend.getUser_2().getUsername());
            } else {
                username.setText(this.friend.getUser_1().getUsername());
            }
        }

        if (data.getPerformative() == ObjectWrapper.REPLY_ADD_FRIEND
                || data.getPerformative() == ObjectWrapper.REPLY_CONFIRM_FRIEND
                || data.getPerformative() == ObjectWrapper.REPLY_CANCEL_FRIEND) {
            if (!(boolean) data.getData()) {
                JOptionPane.showMessageDialog(rootPane, "Error occured");
            } else {
                this.dispose();
            }
        }
    }

    public void resetUI() {
        addBtn.setEnabled(false);
        acceptBtn.setEnabled(false);
        cancelBtn.setEnabled(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetailFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetailFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetailFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetailFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserDetailFrm dialog = new UserDetailFrm(new javax.swing.JFrame(), true, null, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
